baseURL = 'https://teja463.github.io/'
languageCode = 'en-us'
title = 'Teja Blog'

paginate = 2

[params]
    myDateFormat = "Jan 2, 2006"
    description = "Teja blog description"

[taxonomies]
    category = "categories"
    author = "authors"